<?php

function darty_bloc_inline_entity_form_entity_form_submit($entity_form, &$form_state) {
    $ief_id = $entity_form['#ief_id'];
    $instance = $form_state['inline_entity_form'][$ief_id]['instance'];
    // Instantiate the controller and validate the form.
    $controller = inline_entity_form_get_controller($instance);
    $controller->entityFormSubmit($entity_form, $form_state);

    inline_entity_form_cleanup_entity_form_state($entity_form, $form_state);

    if ($entity_form['#op'] == 'add') {
        // Determine the correct weight of the new element.
        $weight = 0;
        if (!empty($form_state['inline_entity_form'][$ief_id]['entities'])) {
            $weight = max(array_keys($form_state['inline_entity_form'][$ief_id]['entities'])) + 1;
        }
        // Add the entity to form state, mark it for saving, and close the form.
        $form_state['inline_entity_form'][$ief_id]['entities'][] = array(
            'entity' => $entity_form['#entity'],
            'weight' => $weight,
            'form' => NULL,
            'needs_save' => TRUE,
        );
    } else {
        $delta = $entity_form['#ief_row_delta'];
        $form_state['inline_entity_form'][$ief_id]['entities'][$delta]['entity'] = $entity_form['#entity'];
        $form_state['inline_entity_form'][$ief_id]['entities'][$delta]['needs_save'] = TRUE;
    }
    if ($entity_form['#entity_type'] == 'bean' && in_array($entity_form['#bundle'], array('bloc_plus_moins', 'bloc_bio_express', 'bloc_edito', 'bloc_forum', 'bloc_lien_rubrique',
                'bloc_remonte_produit', 'bloc_sondage', 'chapitre_article', 'item_diapo',
                'contenu', 'forum', 'mise_en_avant', 'question_quizz'))) {
        if ($entity_form['#entity']->label != '')
            $entity_form['#entity']->title = $entity_form['#entity']->label;
    }
}

function darty_bloc_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'bean_form' && isset($form['#entity'])) {
        $bean = $form['#entity'];
        if ($bean->type == 'bloc_services_darty') {
            $form['label']['#title'] = 'Titre du bloc (affiché)';
            $form['label']['#description'] = "";
            $form['title']['#title'] = 'Nom d\'administration du bloc';
            $form['title']['#description'] = "";
            $form['revision']['#access'] = FALSE;
        }
    }
}

/**
 * Implementation of hook_inline_entity_form_entity_form_alter
 * permet d'alterer la liste de selection du choix de rubrique pour le bloc de droite "lien rubrique"
 * 
 */
function darty_bloc_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {

    if ($entity_form['#entity_type'] == 'bean' && in_array($entity_form['#bundle'], array('bloc_plus_moins', 'bloc_bio_express', 'bloc_edito', 'bloc_forum', 'bloc_lien_rubrique',
                'bloc_remonte_produit', 'bloc_services_darty', 'bloc_sondage', 'chapitre_article', 'item_diapo',
                'contenu', 'forum', 'mise_en_avant', 'question_quizz'))) {
        $entity_form['revision']['#access'] = false;
        $entity_form['default_revision']['#access'] = false;

        if ($entity_form['#bundle'] != 'bloc_services_darty') {
            $entity_form['title']['#access'] = false;
            $entity_form['label']['#title'] = 'Titre';
        } else {
            $entity_form['label']['#title'] = 'Titre du bloc (affiché)';
            $entity_form['title']['#title'] = 'Nom d\'administration du bloc';
        }
        $entity_form['actions']['ief_add_save']['#value'] = 'Créer le bloc';
        $entity_form['actions']['ief_edit_save']['#value'] = 'Modifier le bloc';
        unset($entity_form['#ief_element_submit']);
        $entity_form['#ief_element_submit'][] = 'darty_bloc_inline_entity_form_entity_form_submit';
    }
}

/**
 * @file
 * Code for the Darty_bloc feature.
 */
include_once 'darty_bloc.features.inc';

/**
 * Implementation of template_preprocess_entity
 */
function darty_bloc_preprocess_entity(&$vars) {
    $entity_type = $vars['elements']['#entity_type'];
    $type = $vars['elements']['#bundle'];
    $view_mode = $vars['view_mode'];

//Define some preprocess functions for the field collection field_menu_items
    if ($type == "bloc_bio_express" ||
            $type == "bloc_edito" ||
            $type == "bloc_forum" ||
            $type == "forum" ||
            $type == "bloc_lien_rubrique" ||
            $type == "bloc_plus_moins" ||
            $type == "bloc_remonte_produit" ||
            $type == "bloc_services_darty" ||
            $type == "bloc_sondage" ||
            $type == 'chapitre_article'
    ) {
        $preprocess_type = 'darty_bloc_preprocess_' . $entity_type . '_' . $type;

        $preprocess_type_view_mode = 'darty_bloc_preprocess_' . $entity_type . '_' . $type . '_' . $view_mode;
        if (function_exists($preprocess_type)) {
            $preprocess_type($vars);
        }

        if (function_exists($preprocess_type_view_mode)) {
            $preprocess_type_view_mode($vars);
        }
    }
}

/**
 * Implements darty_bloc_preprocess_bean_bloc_lien_rubrique().
 */
function darty_bloc_preprocess_bean_bloc_lien_rubrique(&$vars) {
    global $conf;
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    $vars['rubrique_info'] = array();
    if (is_object($wrapper)) {


        $rub_avance = $wrapper->field_bloc_choix_rub_avance->value();
        $rub_url = $wrapper->field_bloc_choix_rub_url->value();
        $title = $wrapper->field_bloc_choix_rub_title->value();
        $image = false;
        if (isset($entity->field_bloc_choix_rub_image) && !empty($entity->field_bloc_choix_rub_image)) {
            $sid = $entity->field_bloc_choix_rub_image[LANGUAGE_NONE][0]['sid'];
            $obj_atom = scald_atom_load($sid);
            if (isset($obj_atom) && isset($obj_atom->scald_thumbnail[LANGUAGE_NONE][0])) {
                $image = '<img src="' . file_create_url($obj_atom->scald_thumbnail[LANGUAGE_NONE][0]['uri']) . '" alt="' . $obj_atom->scald_thumbnail[LANGUAGE_NONE][0]['alt'] . '"></img>';
            }
        }
        $rub_avance2 = $wrapper->field_bloc_choix_rub2_avance->value();
        $rub2_url = $wrapper->field_bloc_choix_rub2_url->value();
        $title2 = $wrapper->field_bloc_choix_rub2_title->value();
        $rub_ids[] = array('rub' => $rub_avance, 'title' => $title, 'url' => $rub_url, 'image' => $image);
        if (!empty($rub_avance2))
            $rub_ids[] = array('rub' => $rub_avance2, 'title' => $title2, 'url' => $rub2_url, 'image' => false);

        foreach ($rub_ids as $item) {
            $rub = array();

            $rub['title'] = $item['title'];
            $rub['image'] = $item['image'];
            $url_avance = pathinfo($item['rub']);
            preg_match('/.*[?](.*)/', $url_avance['basename'], $matches);
            if (isset($item['url']) && !empty($item['url']))
                    $rub['url'] = $item['url'];
                else
                    $rub['url'] = $item['rub'];
                
            $cache = cache_get('info_rubrique_' . md5($item['rub']));
            if ($cache && $cache->expire > time()) {
                $data_encode = $cache->data;
            } else {
                if (isset($conf['darty_header_htaccess']) && !empty($conf['darty_header_htaccess']))
                    $url_tmp = $conf['darty_header_protocol'] . $conf['darty_header_htaccess'] . '@' . $conf['darty_api_url'];
                else
                    $url_tmp = $conf['darty_header_protocol'] . $conf['darty_api_url'];

                $navUrl = $url_tmp . '/nav?query=' . $matches[1];
                $navUrl_code = $url_tmp . '/nav?query=' . str_replace('&', '%26', $matches[1]);
                
                $options = array('method' => 'GET');
                $result_more = drupal_http_request($navUrl_code, $options);
                if (!isset($result_more) || !isset($result_more->data)) {

                    $result_more = drupal_http_request($navUrl, $options);
                   
                }
                $data_encode = $result_more->data;
                cache_set('info_rubrique_' . md5($item['rub']), $data_encode, 'cache', time() + 300);
            }
            $json_more = json_decode($data_encode);
            $rub['count'] = (isset($json_more->resultCount)) ? $json_more->resultCount : 0;
            $rub['minPrice'] = (isset($json_more->minPrice)) ? $json_more->minPrice : 0;
            $rub['maxPrice'] = (isset($json_more->maxPrice)) ? $json_more->maxPrice : 0;

            $vars['rubrique_info'][] = $rub;
        }
    }
}

/**
 * Implements darty_bloc_preprocess_bean_forum().
 */
function darty_bloc_preprocess_bean_forum(&$vars) {
    global $conf;
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    if (is_object($wrapper)) {
        //post or user
        $vars['type'] = $wrapper->field_type_forum_bloc->value();

        $cache = cache_get('forum_36000_' . $vars['type']);
        if ($cache && $cache->expire > time()) {
            $data_encode = $cache->data;
        } else {
            if ($vars['type'] == 'user')
                $navUrl = $conf['36000_api_protocol'].$conf['36000_api_url'].'/api.php/utilisateurs/listeexperts.json';
            else if ($vars['type'] == 'post')
                $navUrl = $conf['36000_api_protocol'].$conf['36000_api_url'].'/api.php/questions/lastanswered.json';
            $options = array('method' => 'GET');
            $result_more = drupal_http_request($navUrl, $options);
            if (isset($result_more) && isset($result_more->data)) {
                $data_encode = $result_more->data;
                cache_set('forum_36000_' . $vars['type'], $data_encode, 'cache', time() + 3600);
            }
        }
        if (isset($data_encode) && !empty($data_encode)){
            $json_more = drupal_json_decode($data_encode);

            if ($vars['type'] == 'user'){
                $rd = rand(0, count($json_more)-1);
                $vars['user'] = $json_more[$rd];
            }elseif($vars['type'] == 'post'){
                if (isset($json_more[0])){
                    $vars['contenu'] = $json_more[0]['contenu'];
                    $vars['link'] = $json_more[0]['frontendLink'];
                }
            }
        }else{
            $vars['error'] = true;
        }
    }
}

/**
 * Implements darty_bloc_preprocess_bean_bloc_remonte_produit().
 */
function darty_bloc_preprocess_bean_bloc_remonte_produit(&$vars) {
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    if (is_object($wrapper)) {
        $codics = $wrapper->field_bloc_codics->value();

        $vars['products'] = get_info_produits($codics);
    }
}

function _wrapper_debug($w) {
    $values = array();
    foreach ($w->getPropertyInfo() as $key => $val) {
        $values[$key] = $w->$key->value();
    }
    return $values;
}

/**
 * Implements darty_bloc_preprocess_bean_bloc_services_darty().
 */
function darty_bloc_preprocess_bean_bloc_services_darty(&$vars) {
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    if (is_object($wrapper)) {
        $vars['titre'] = $entity->label;
        $arrayTexte = $wrapper->field_bloc_texte->value();
        $vars['texte'] = (isset($arrayTexte) && is_array($arrayTexte)) ? $arrayTexte['safe_value'] : $arrayTexte;

        $objPortrait = $wrapper->field_bloc_image->value();
        $vars['image'] = (!empty($objPortrait)) ? scald_render($objPortrait->sid, 'darty_context_90_x_90') : '';
        if (isset($wrapper->field_field_bloc_bool_titre)) {
            $bool_titre = $wrapper->field_field_bloc_bool_titre->value();
            $vars['bool_titre'] = $bool_titre;
        }

        $lien = $wrapper->field_bloc_lien->value();
        $vars['lien'] = !empty($lien) ? l($lien['title'], $lien['url'], array('attributes' => $lien['attributes'])) : '';
    }
}

/**
 * Implements darty_bloc_preprocess_bean_bloc_bio_express().
 */
function darty_bloc_preprocess_bean_bloc_edito(&$vars) {
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    if (is_object($wrapper)) {

        $vars['titre'] = $wrapper->label->value();
        $arrayTexte = $wrapper->field_bloc_texte->value();
        if (isset($arrayTexte) && is_array($arrayTexte))
            $vars['texte'] = $arrayTexte['safe_value'];
    }
}

/**
 * Implements darty_bloc_preprocess_bean_bloc_bio_express().
 */
function darty_bloc_preprocess_bean_bloc_bio_express(&$vars) {
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    if (is_object($wrapper)) {
        $vars['titre'] = $wrapper->label->value();
        $objPortrait = $wrapper->field_bloc_image->value();
        $vars['portrait'] = scald_render($objPortrait->sid, 'portrait_160_160');
        $arrayTexte = $wrapper->field_bloc_texte->value();
        if (isset($arrayTexte) && is_array($arrayTexte))
            $vars['texte'] = $arrayTexte['safe_value'];
    }
}

/**
 * Implements darty_bloc_preprocess_bean_bloc_plus_moins().
 */
function darty_bloc_preprocess_bean_bloc_plus_moins(&$vars) {
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    if (is_object($wrapper)) {
        $vars['title_plus'] = $wrapper->field_titre_les_plus->value();
        $vars['title_moins'] = $wrapper->field_titre_les_moins->value();
        $vars['liste_plus'] = $wrapper->field_liste_elem_plus->value();
        $vars['liste_moins'] = $wrapper->field_liste_elem_moins->value();
    }
//bean-bloc-plus-moins
//
//plus-wrapper
//moins-wrapper

    drupal_add_js(
            "jQuery(document).ready(function () { 
var hPlus = jQuery('.bean-bloc-plus-moins .plus-wrapper').first().height();
var hMoins = jQuery('.bean-bloc-plus-moins .moins-wrapper').first().height();
if (hPlus > hMoins) jQuery('.bean-bloc-plus-moins .moins-wrapper').first().height(hPlus);
else jQuery('.bean-bloc-plus-moins .plus-wrapper').first().height(hMoins);
});", array('type' => 'inline', 'scope' => 'footer')
    );
}

/**
 * Implements darty_bloc_preprocess_bean_chapitre_article().
 */
function darty_bloc_preprocess_bean_chapitre_article(&$vars) {
    $entity = $vars['elements']['#entity'];
    $wrapper = entity_metadata_wrapper('bean', $entity);

    $id = $vars['view_mode'];
    preg_match('/sommaire_([0-9]*)_([0-9]*)/', $id, $matches);
    $pos = $matches[1];
    $total = $matches[2];

    if (is_object($wrapper)) {
        $vars['titre'] = $wrapper->label->value();
        $arrayTexte = $wrapper->field_contenu_chapitre->value();
        if (isset($arrayTexte) && is_array($arrayTexte))
            $texte = $arrayTexte['safe_value'];
        else
            $texte = $arrayTexte;
        $vars['texte'] = $texte;
        $vars['id'] = $vars['view_mode'];
        $vars['pos'] = $pos;
        $vars['total'] = $total;

        drupal_add_js(drupal_get_path('module', 'darty_bloc') . "/js/sommaire.js", array('type' => 'file', 'scope' => 'footer'));
    }
}

function darty_bloc_menu() {

    $items['admin/bloc_services'] = array(
        'title' => 'Listing de tous les blocs services',
        'page callback' => 'listing_bloc_services',
        'page arguments' => array(),
        'access callback' => 'access_listing_services',
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function darty_bloc_permission() {
    return array(
        'listing services' => array(
            'title' => t('Autoriser à voir le listing des blocs services')
        )
    );
}

function listing_bloc_services() {
    return 'listing';
}

function access_listing_services() {
    return user_access('listing services');
}