<?php
/**
 * @file
 * quizz_features.bean.inc
 */

/**
 * Implements hook_bean_admin_ui_types().
 */
function quizz_features_bean_admin_ui_types() {
  $export = array();

  $bean_type = new stdClass();
  $bean_type->disabled = FALSE; /* Edit this to true to make a default bean_type disabled initially */
  $bean_type->api_version = 5;
  $bean_type->name = 'question_quizz';
  $bean_type->label = 'Question_quizz';
  $bean_type->options = '';
  $bean_type->description = '';
  $export['question_quizz'] = $bean_type;

  return $export;
}
